# Generated by Django 4.1.4 on 2022-12-21 08:51

import django.core.validators
from django.db import migrations, models
import my_plant.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), my_plant.core.validators.validate_only_letters]),
        ),
    ]
